name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Set this to your .NET SDK version

    - name: Restore dependencies
      working-directory: ./GithubWorkflowSample
      run: dotnet restore

    - name: Build
      working-directory: ./GithubWorkflowSample
      run: dotnet build --no-restore

    - name: Test
      working-directory: ./GithubWorkflowSample
      run: dotnet test --no-build